const products = [
  {
    id: '1',
    name: 'Portable Neck Fan - USB Rechargeable',
    description: 'Hanging neck fan with bladeless design – perfect for kitchen, travel, or outdoor use.',
    price: 989,
    originalPrice: 3499,
    discount: '72%',
    category: 'Portable Fans',
    brand: 'No Brand',
    rating: 4.2,
    reviews: 219,
    questionsAnswered: 34,
    deliveryFee: 160,
    deliveryEstimate: '28-31 Jul',
    returnPolicy: '14 days easy return',
    warranty: 'No warranty available',
    location: 'Karachi, Pakistan',
    cashOnDelivery: true
  },
  {
    id: '2',
    name: 'Mini USB Rechargeable Fan',
    description: 'Small desk fan with USB charging, ideal for study or office use.',
    price: 599,
    originalPrice: 1299,
    discount: '54%',
    category: 'Portable Fans',
    brand: 'Generic',
    rating: 4.0,
    reviews: 105,
    questionsAnswered: 17,
    deliveryFee: 150,
    deliveryEstimate: '27-30 Jul',
    returnPolicy: '7 days return',
    warranty: 'No warranty',
    location: 'Lahore, Pakistan',
    cashOnDelivery: true,
  },
  {
    id: '3',
    name: 'Wireless Neckband Fan with LED',
    description: 'Fashionable neck fan with soft LED lights and quiet operation.',
    price: 1249,
    originalPrice: 2499,
    discount: '50%',
    category: 'Portable Fans',
    brand: 'CoolBreeze',
    rating: 4.5,
    reviews: 320,
    questionsAnswered: 45,
    deliveryFee: 180,
    deliveryEstimate: '29 Jul - 1 Aug',
    returnPolicy: '15 days return',
    warranty: '1 month local warranty',
    location: 'Islamabad, Pakistan',
    cashOnDelivery: true,
  },
  {
    id: '4',
    name: 'Handheld Misting Fan - 3 Speed',
    description: 'Portable fan with water mist function for instant cooling relief.',
    price: 1299,
    originalPrice: 2599,
    discount: '50%',
    category: 'cooling',
    brand: 'BreezePro',
    rating: 4.3,
    reviews: 178,
    questionsAnswered: 29,
    deliveryFee: 170,
    deliveryEstimate: '30 Jul - 2 Aug',
    returnPolicy: '10 days return',
    warranty: '2 months warranty',
    location: 'Rawalpindi, Pakistan',
    cashOnDelivery: false
  },
  {
    id: '5',
    name: 'Clip-on Desk Fan with USB',
    description: 'Adjustable clip fan perfect for beds, desks, or strollers.',
    price: 749,
    originalPrice: 1499,
    discount: '50%',
    category: 'USB',
    brand: 'AirCool',
    rating: 3.9,
    reviews: 87,
    questionsAnswered: 12,
    deliveryFee: 140,
    deliveryEstimate: '26-29 Jul',
    returnPolicy: '7 days return',
    warranty: 'No warranty',
    location: 'Faisalabad, Pakistan',
    cashOnDelivery: true
  },
  {
    id: '6',
    name: 'Rechargeable Standing Floor Fan',
    description: 'Tall portable fan with adjustable height and 360° rotation.',
    price: 1999,
    originalPrice: 3999,
    discount: '50%',
    category: 'Portable Fans',
    brand: 'WindMaster',
    rating: 4.6,
    reviews: 412,
    questionsAnswered: 63,
    deliveryFee: 200,
    deliveryEstimate: '1-4 Aug',
    returnPolicy: '15 days return',
    warranty: '3 months warranty',
    location: 'Peshawar, Pakistan',
    cashOnDelivery: true
  },
  {
    id: '7',
    name: 'Mini Foldable Hand Fan with Power Bank',
    description: 'Ultra-compact fan that doubles as a phone charger.',
    price: 899,
    originalPrice: 1999,
    discount: '55%',
    category: 'Portable Fans',
    brand: 'TechBreeze',
    rating: 4.1,
    reviews: 156,
    questionsAnswered: 24,
    deliveryFee: 150,
    deliveryEstimate: '27-30 Jul',
    returnPolicy: '10 days return',
    warranty: '1 month warranty',
    location: 'Multan, Pakistan',
    cashOnDelivery: false
  },
  {
    id: '8',
    name: 'Smart Neck Fan with App Control',
    description: 'Bluetooth enabled neck fan with adjustable speed via mobile app.',
    price: 2499,
    originalPrice: 4999,
    discount: '50%',
    category: 'Portable Fans',
    brand: 'SmartCool',
    rating: 4.7,
    reviews: 289,
    questionsAnswered: 51,
    deliveryFee: 220,
    deliveryEstimate: '2-5 Aug',
    returnPolicy: '30 days return',
    warranty: '6 months warranty',
    location: 'Karachi, Pakistan',
    cashOnDelivery: true
  },
  {
    id: '9',
    name: 'Battery Operated Table Fan',
    description: 'Lightweight fan runs on AA batteries, perfect for power outages.',
    price: 649,
    originalPrice: 1299,
    discount: '50%',
    category: 'Portable Fans',
    brand: 'PowerBreeze',
    rating: 3.8,
    reviews: 94,
    questionsAnswered: 15,
    deliveryFee: 130,
    deliveryEstimate: '25-28 Jul',
    returnPolicy: '7 days return',
    warranty: 'No warranty',
    location: 'Hyderabad, Pakistan',
    cashOnDelivery: true
  },
  {
    id: '10',
    name: 'Premium Dual Head Neck Fan',
    description: 'Ergonomic design with two adjustable cooling zones.',
    price: 1799,
    originalPrice: 3599,
    discount: '50%',
    category: 'Portable Fans',
    brand: 'ArcticFlow',
    rating: 4.4,
    reviews: 203,
    questionsAnswered: 38,
    deliveryFee: 190,
    deliveryEstimate: '31 Jul - 3 Aug',
    returnPolicy: '14 days return',
    warranty: '3 months warranty',
    location: 'Quetta, Pakistan',
    cashOnDelivery: true
  }
];

module.exports = products;